name: Deploy to EC2 on merge

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH key
              uses: webfactory/ssh-agent@v0.6.0
              with:
                ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

            - name: deploy to ec2
              run: |
                ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_IP }} << 'EOF'
                  echo "Hello from github action, start deploy main to ec2"
                  export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v22.3.0/bin
                  cd ~/MyTravel
                  git switch main
                  git pull
                  cd client
                  which parcel || echo "Parcel not found in PATH"
                  npx parcel serve blog.html
                  cd ../server
                  which npm
                  which pm2
                  npm install
                  pm2 restart index
                EOF
